#관리자 권한 갖기
sudo: required

#언어(플랫폼) 선택
language: generic

#도커 환경 구성
services:
    - docker

#스크립트를 실행할 수 있는 환경 구성
before_install:
    - echo "start creating an image with dockerfile"
    - docker build -t gustj3104/docker-react-app -f Dockerfile.dev .

#실행할 스크립트(테스트 실행)
script:
    - docker run -e CI=true gustj3104/docker-react-app npm run test -- --coverage

#테스트 성공 후 할 일
after_success:
    - echo "Test Success"

deploy:
    edge: true
    provider: elasticbeanstalk
    region: ap-northest-2
    app: docker-react-app
    env: DockerReactApp-env
    bucket-name: elasticbeanstalk-ap-northest-2-972153559337
    bucket-path: docker-react-app
    on:
        branch: master
